import React, { useState } from 'react'
import { Link2, FileText } from 'lucide-react'

const VideoSummarizerPage: React.FC = () => {
  const [videoUrl, setVideoUrl] = useState('')
  const [summary, setSummary] = useState('')

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault()
    if (!videoUrl) return

    // In a real application, you would send the video URL to a backend service for processing
    // For this example, we'll simulate a summary after a short delay
    setSummary('Generating summary...')
    await new Promise(resolve => setTimeout(resolve, 2000))
    setSummary('This is a simulated summary of the video content. In a real application, this would be generated by processing the video and extracting key points.')
  }

  return (
    <div className="max-w-2xl mx-auto bg-white rounded-xl shadow-md overflow-hidden">
      <div className="p-8">
        <h2 className="text-2xl font-bold mb-4">Video Summarizer</h2>
        <form onSubmit={handleSubmit} className="mb-6">
          <div className="mb-4">
            <label htmlFor="video-url" className="block text-sm font-medium text-gray-700 mb-2">
              Video URL
            </label>
            <div className="mt-1 relative rounded-md shadow-sm">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Link2 className="h-5 w-5 text-gray-400" />
              </div>
              <input
                type="url"
                id="video-url"
                className="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-10 sm:text-sm border-gray-300 rounded-md"
                placeholder="https://www.youtube.com/watch?v=..."
                value={videoUrl}
                onChange={(e) => setVideoUrl(e.target.value)}
                required
              />
            </div>
          </div>
          <button
            type="submit"
            className="w-full px-4 py-2 bg-indigo-500 text-white rounded-md hover:bg-indigo-600 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            disabled={!videoUrl}
          >
            Summarize Video
          </button>
        </form>
        {summary && (
          <div className="mt-6">
            <h3 className="text-lg font-semibold mb-2">Summary</h3>
            <div className="bg-gray-100 p-4 rounded-md">
              <FileText className="w-6 h-6 text-indigo-500 mb-2" />
              <p className="text-gray-700">{summary}</p>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default VideoSummarizerPage